# change C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

#bind the refresh of the source file
bind r source-file ~/.tmux.conf

# split panes using | and -
bind é split-window -h -c "#{pane_current_path}"
bind ö split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
unbind '"'
unbind %

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

bind C-é send-keys 'C-l'

set -g status off
