#!/bin/bash
if [ "$1" == "prompt" ]; then
	text=$(python3 ~/python/dialog.py)
	task add $text
elif [ "$1" == "task" ]; then
	pkill -x teams
	task
	echo "task/>"
	while read task
	do
		clear
		task $task
		echo "task/>"
	done 
elif [ "$1" == "calendar" ]; then
	task calendar
	while read task
	do
		task $task
	done 
elif [ "$1" == "evenement" ]; then
	date=$(python3 ~/python/calendar.py)
	text=$(python3 ~/python/dialog.py)
	task add $text due:$date
else
	path=$(pwd)
	project="project:$(python3 -c "print('$path'.split('/')[4])")"
	while read task
	do
		task add $1 $task $project
	done 
fi
